// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: build_log.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImageReference) Reset() {
	*x = ImageReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageReference) ProtoMessage() {}

func (x *ImageReference) ProtoReflect() protoreflect.Message {
	mi := &file_build_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageReference.ProtoReflect.Descriptor instead.
func (*ImageReference) Descriptor() ([]byte, []int) {
	return file_build_log_proto_rawDescGZIP(), []int{0}
}

type PartReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PartReference) Reset() {
	*x = PartReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartReference) ProtoMessage() {}

func (x *PartReference) ProtoReflect() protoreflect.Message {
	mi := &file_build_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartReference.ProtoReflect.Descriptor instead.
func (*PartReference) Descriptor() ([]byte, []int) {
	return file_build_log_proto_rawDescGZIP(), []int{1}
}

type ManualReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ManualReference) Reset() {
	*x = ManualReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManualReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualReference) ProtoMessage() {}

func (x *ManualReference) ProtoReflect() protoreflect.Message {
	mi := &file_build_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualReference.ProtoReflect.Descriptor instead.
func (*ManualReference) Descriptor() ([]byte, []int) {
	return file_build_log_proto_rawDescGZIP(), []int{2}
}

type TaskDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string             `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Images      []*ImageReference  `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Parts       []*PartReference   `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	Manuals     []*ManualReference `protobuf:"bytes,4,rep,name=manuals,proto3" json:"manuals,omitempty"`
}

func (x *TaskDetails) Reset() {
	*x = TaskDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetails) ProtoMessage() {}

func (x *TaskDetails) ProtoReflect() protoreflect.Message {
	mi := &file_build_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetails.ProtoReflect.Descriptor instead.
func (*TaskDetails) Descriptor() ([]byte, []int) {
	return file_build_log_proto_rawDescGZIP(), []int{3}
}

func (x *TaskDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskDetails) GetImages() []*ImageReference {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *TaskDetails) GetParts() []*PartReference {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *TaskDetails) GetManuals() []*ManualReference {
	if x != nil {
		return x.Manuals
	}
	return nil
}

type BuildWorkEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary string         `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Details []*TaskDetails `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *BuildWorkEntry) Reset() {
	*x = BuildWorkEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildWorkEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildWorkEntry) ProtoMessage() {}

func (x *BuildWorkEntry) ProtoReflect() protoreflect.Message {
	mi := &file_build_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildWorkEntry.ProtoReflect.Descriptor instead.
func (*BuildWorkEntry) Descriptor() ([]byte, []int) {
	return file_build_log_proto_rawDescGZIP(), []int{4}
}

func (x *BuildWorkEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BuildWorkEntry) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *BuildWorkEntry) GetDetails() []*TaskDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type BuildLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Work      *BuildWorkEntry        `protobuf:"bytes,4,opt,name=work,proto3" json:"work,omitempty"`
}

func (x *BuildLogEntry) Reset() {
	*x = BuildLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogEntry) ProtoMessage() {}

func (x *BuildLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_build_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogEntry.ProtoReflect.Descriptor instead.
func (*BuildLogEntry) Descriptor() ([]byte, []int) {
	return file_build_log_proto_rawDescGZIP(), []int{5}
}

func (x *BuildLogEntry) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildLogEntry) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BuildLogEntry) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *BuildLogEntry) GetWork() *BuildWorkEntry {
	if x != nil {
		return x.Work
	}
	return nil
}

var File_build_log_proto protoreflect.FileDescriptor

var file_build_log_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a,
	0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22,
	0x0f, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75,
	0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e,
	0x63, 0x75, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x61, 0x6e, 0x75,
	0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x72, 0x62,
	0x6f, 0x6e, 0x63, 0x75, 0x62, 0x2e, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x73, 0x22, 0x72,
	0x0a, 0x0e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x12, 0x30, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x22, 0xc0, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x6f, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62,
	0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x67, 0x63, 0x72, 0x61, 0x69, 0x67, 0x2f, 0x63, 0x61,
	0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2d, 0x6c, 0x6f,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_build_log_proto_rawDescOnce sync.Once
	file_build_log_proto_rawDescData = file_build_log_proto_rawDesc
)

func file_build_log_proto_rawDescGZIP() []byte {
	file_build_log_proto_rawDescOnce.Do(func() {
		file_build_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_build_log_proto_rawDescData)
	})
	return file_build_log_proto_rawDescData
}

var file_build_log_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_build_log_proto_goTypes = []interface{}{
	(*ImageReference)(nil),        // 0: carboncub.ImageReference
	(*PartReference)(nil),         // 1: carboncub.PartReference
	(*ManualReference)(nil),       // 2: carboncub.ManualReference
	(*TaskDetails)(nil),           // 3: carboncub.TaskDetails
	(*BuildWorkEntry)(nil),        // 4: carboncub.BuildWorkEntry
	(*BuildLogEntry)(nil),         // 5: carboncub.BuildLogEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_build_log_proto_depIdxs = []int32{
	0, // 0: carboncub.TaskDetails.images:type_name -> carboncub.ImageReference
	1, // 1: carboncub.TaskDetails.parts:type_name -> carboncub.PartReference
	2, // 2: carboncub.TaskDetails.manuals:type_name -> carboncub.ManualReference
	3, // 3: carboncub.BuildWorkEntry.details:type_name -> carboncub.TaskDetails
	6, // 4: carboncub.BuildLogEntry.start_time:type_name -> google.protobuf.Timestamp
	6, // 5: carboncub.BuildLogEntry.end_time:type_name -> google.protobuf.Timestamp
	4, // 6: carboncub.BuildLogEntry.work:type_name -> carboncub.BuildWorkEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_build_log_proto_init() }
func file_build_log_proto_init() {
	if File_build_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_build_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManualReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildWorkEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_build_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_build_log_proto_goTypes,
		DependencyIndexes: file_build_log_proto_depIdxs,
		MessageInfos:      file_build_log_proto_msgTypes,
	}.Build()
	File_build_log_proto = out.File
	file_build_log_proto_rawDesc = nil
	file_build_log_proto_goTypes = nil
	file_build_log_proto_depIdxs = nil
}
