// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: log_metadata.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildLogEntryMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Top-level component, i.e., "left wing"
	Assembly string `protobuf:"bytes,1,opt,name=assembly,proto3" json:"assembly,omitempty"`
	// Next-level components i.e., "center ribs"
	Subassembly []string               `protobuf:"bytes,2,rep,name=subassembly,proto3" json:"subassembly,omitempty"`
	StartTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LogFilename string                 `protobuf:"bytes,5,opt,name=log_filename,json=logFilename,proto3" json:"log_filename,omitempty"`
	Tags        []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *BuildLogEntryMetadata) Reset() {
	*x = BuildLogEntryMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildLogEntryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogEntryMetadata) ProtoMessage() {}

func (x *BuildLogEntryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_log_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogEntryMetadata.ProtoReflect.Descriptor instead.
func (*BuildLogEntryMetadata) Descriptor() ([]byte, []int) {
	return file_log_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *BuildLogEntryMetadata) GetAssembly() string {
	if x != nil {
		return x.Assembly
	}
	return ""
}

func (x *BuildLogEntryMetadata) GetSubassembly() []string {
	if x != nil {
		return x.Subassembly
	}
	return nil
}

func (x *BuildLogEntryMetadata) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BuildLogEntryMetadata) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *BuildLogEntryMetadata) GetLogFilename() string {
	if x != nil {
		return x.LogFilename
	}
	return ""
}

func (x *BuildLogEntryMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type BuildLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*BuildLogEntryMetadata `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *BuildLogs) Reset() {
	*x = BuildLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogs) ProtoMessage() {}

func (x *BuildLogs) ProtoReflect() protoreflect.Message {
	mi := &file_log_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogs.ProtoReflect.Descriptor instead.
func (*BuildLogs) Descriptor() ([]byte, []int) {
	return file_log_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *BuildLogs) GetEntries() []*BuildLogEntryMetadata {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_log_metadata_proto protoreflect.FileDescriptor

var file_log_metadata_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x6f, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xfe, 0x01, 0x0a, 0x15, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x73,
	0x73, 0x65, 0x6d, 0x62, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73,
	0x73, 0x65, 0x6d, 0x62, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x61, 0x73, 0x73,
	0x65, 0x6d, 0x62, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62,
	0x61, 0x73, 0x73, 0x65, 0x6d, 0x62, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f,
	0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x47, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x3a,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x67, 0x63, 0x72, 0x61,
	0x69, 0x67, 0x2f, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x63, 0x75, 0x62, 0x2d, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x2d, 0x6c, 0x6f, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_metadata_proto_rawDescOnce sync.Once
	file_log_metadata_proto_rawDescData = file_log_metadata_proto_rawDesc
)

func file_log_metadata_proto_rawDescGZIP() []byte {
	file_log_metadata_proto_rawDescOnce.Do(func() {
		file_log_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_metadata_proto_rawDescData)
	})
	return file_log_metadata_proto_rawDescData
}

var file_log_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_log_metadata_proto_goTypes = []interface{}{
	(*BuildLogEntryMetadata)(nil), // 0: carboncub.BuildLogEntryMetadata
	(*BuildLogs)(nil),             // 1: carboncub.BuildLogs
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_log_metadata_proto_depIdxs = []int32{
	2, // 0: carboncub.BuildLogEntryMetadata.start_time:type_name -> google.protobuf.Timestamp
	2, // 1: carboncub.BuildLogEntryMetadata.end_time:type_name -> google.protobuf.Timestamp
	0, // 2: carboncub.BuildLogs.entries:type_name -> carboncub.BuildLogEntryMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_log_metadata_proto_init() }
func file_log_metadata_proto_init() {
	if File_log_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_log_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildLogEntryMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_log_metadata_proto_goTypes,
		DependencyIndexes: file_log_metadata_proto_depIdxs,
		MessageInfos:      file_log_metadata_proto_msgTypes,
	}.Build()
	File_log_metadata_proto = out.File
	file_log_metadata_proto_rawDesc = nil
	file_log_metadata_proto_goTypes = nil
	file_log_metadata_proto_depIdxs = nil
}
